repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.15.0
    hooks:
    - id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    - id: black
      args: [--line-length=79]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    - id: flake8
      args: ["--exclude", "examples/*"]
-   repo: https://github.com/PyCQA/bandit
    rev: '1.8.6'
    hooks:
    - id: bandit
      args: ["--exclude", "tests/*"]
-   repo: local
    hooks:
    - id: grep-for-devtools
      name: Check for devtools in fractal_client files
      entry: bash -c 'for file in "$@"; do if grep -n "devtools" "$file"; then echo "$file" && exit 1; fi; done' --
      language: system
      files: fractal_client/
